name: spm

on:
  push:
  pull_request:

jobs:
  swift-build-run:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Xcode 12
      run: sudo xcode-select -s /Applications/Xcode_12_beta.app/Contents/Developer
    - name: Build
      run: swift build
    - name: Run
      run: swift test
